version: "3.9"
services:
  web:
    build: .
    container_name: student_app_web
    ports:
      - "8080:80"              # App available at http://localhost:8080
    depends_on:
      - db
    volumes:
      - .:/var/www/html        # Live code updates

  db:
    image: mysql:8.0
    container_name: student_app_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: student_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # auto table creation

volumes:
  db_data:

